### ISSUE TITLE
¿Qué pasa cuando ninguna sede tiene una pieza requerida?

### ISSUE THREAD

**Issue by evaanngiil** [lmchaves/OrganizarTaller#19]
Los pedidos (como indica la HU 1) lo maneja el jefe del taller que es el encargado de hacer que todas las sedes tengan piezas. Por lo que entiendo que si a una sede le falta una pieza que otra sede tiene de sobra, se la pedirá 
Sin embargo, no se especifica qué pasaría si ninguna sede tiene una pieza requerida. ¿Qué pasaría en ese caso? @lmchaves

**Comment by lmchaves** [comment]
Como tal el taller es una sede principal, y este le pide las piezas al resto de sedes(en concreto son 3 mas), y en estas sedes estan las piezas necesarias, cada una con un precio distinto.

**Comment by evaanngiil** [comment]
Es decir que entre las sedes "secundarias" no se envían piezas entre ellas, ¿siempre es todas al taller? En tal caso, si alguna de las sedes secundarias se queda sin piezas, ¿qué pasaría?

**Comment by lmchaves** [comment]
Pues como tal habría que esperar a que en una sede de esas sedes pidan la piezas necesarias y las tengan disponible.

**Comment by evaanngiil** [comment]
¿Y ese pedido se encargaría de hacerlo nuestra aplicación o es externo?

**Comment by lmchaves** [comment]
Ese ya es externo, en nuestra aplicación es como tal las sede principal a las otras 3.

**Comment by JJ** [comment]
No se cierra nunca desde el formulario, *siempre* desde un commit.

**Comment by evaanngiil** [comment]
@JJ El commit relacionado a este issue ya se realizó, lo que solo le asigné un issue que resolvía ¿qué debo hacer?

**Comment by JJ** [comment]
Lo que *no* debes hacer es cerrar desde fuera de un commit o un PR cuando se fusione. A partir de ahí, tienes varias opciones. Infórmate y las llevas a cabo. Si dejas esto cerradon sin un commit a partir de ahora @lmchaves tendrá siempre error cuando envíe los nuevos objetivos.

**Comment by JJ** [comment]
Esto le va a dar error siempre a @lmchaves Se cierra siempre desde un commit.

**Comment by lmchaves** [comment]
@JJ entonces todavía no puedo hacer merge no?

**Comment by JJ** [comment]
Puedes cerrar indicando desde el PR "closes (este número) porque no se va a hacer" *en el cuerpo del PR*. En el momento que mergees, se cierra esto.
