### ISSUE TITLE
Elección del lenguaje de programación

### ISSUE THREAD

**Issue by evaanngiil** [lmchaves/OrganizarTaller#9]
Buenas @lmchaves, debemos ponernos de acuerdo sobre qué lenguaje de programación sería el más adecuado para este proyecto ¿Qué lenguaje crees que sería el que mejor se adapta a tus necesidades?

**Comment by lmchaves** [comment]
Buenas, @evaanngiil, había pensado usar GO, ya que es fácil de aprender, es fácilmente escalable y muy eficiente.

**Comment by evaanngiil** [comment]
Es una buena opción @lmchaves . Pero me gustaría trabajar con algún lenguaje con el que haya desarrollado antes. ¿Qué te parece Python? Tiene las mismas características que deseas en un lenguaje de programación.

**Comment by lmchaves** [comment]
Vale, si quieres usar un lenguaje con el que hayas trabajado, me parece bien con Python.

**Comment by evaanngiil** [comment]
👍🏼

**Comment by evaanngiil** [comment]
Resuelto
